blog/config/routes.rb
Rails.application.routes.draw do

  resources :user

  resources :articles do 
    resources :comments
  end

  get 'test_form/index'
  post 'test_form/create'

  get 'welcome/index'
  get 'welcome/about_us'
  root 'welcome#index'

  get 'login' => 'sessions#index'
  post 'login' => 'sessions#login'
  delete 'logout' => 'sessions#logout'

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments


	validates :title, presence: true
	validates :text, presence: true
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", small:"48x48", tiny:"32x32"}, default_url: ":style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :comments


  EMAIL_REGEX = /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\Z/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password_digest, :confirmation => true #password_confirmation attr
  validates_length_of :password_digest, :in => 6..20, :on => :create


   def authenticate (password)
     self.password_digest == password
   end

  has_secure_password
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  # redirect to login if not logged in
  def authorize
    redirect_to '/login' unless logged_in
  end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # add authentication for all actions
  before_filter :authorize

  # show all articles
  def index
    @articles = Article.all
  end

  # get form page for creating
  def new
  end

  # post action to create a new article
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  # show specific article
  def show
    @article = Article.find(params[:id]);
  end

  # get article for edit
  def edit
    @article = Article.find(params[:id])
  end

  # post action for editing article
  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  # delete specific article
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

# get article object from http params
  private def article_params
    params.require(:article).permit(:title, :text)
  end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.new(comment_params)
		@comment.user = current_user
		@comment.save
		redirect_to article_path(@article)
	end

	private
	def comment_params
		params.require(:comment).permit(:body)
	end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # get login form
  def index
    if logged_in
      redirect_to articles_path
    end
    @user = User.new
  end

  # login user with credentials
  def login
    @user = User.find_by(username: params[:session][:username].downcase)

    if @user && @user.authenticate(params[:session][:password])
      #Log the user in and regirect to the article page
      log_in @user
      redirect_to articles_path
    else
    #show error message that user is invalid
      flash.now[:error] = 'Invalid username/password'
      render 'index'
    end
  end

  # logout
  def logout
    log_out
    redirect_to login_path
  end

end

blog/app/controllers/test_form_controller.rb
class TestFormController < ApplicationController
  def index
  end

  def create
  	render plain: params[:test_form]
  end

end

blog/app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authorize, :except => [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render 'new'
    end
     
  end

  def edit
    @user = User.find(current_user.id)

  end

  def update
    @user = User.find(current_user.id)
   if !@user.update(user_params)
      render 'edit'
   end
  end

  # get article object from http params
  private 
  def user_params
    params.require(:user).permit(:name, :username, :email, :password_digest, :image)
  end

end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def about_us
  	@names = ["bilal","muctadir","chen","manpriya","rasmus"]
  end

end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
  #log in the user
  def log_in(user)
    session[:user_id] = user.id
  end

  #return the current logged in user
  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
    @current_user
    end
  end

  #return true if user is logged in already
  def logged_in()
    !current_user.nil?
  end

  #destroy the session and every detail about the user
  def log_out()
    session.delete(:user_id)
    @current_user = nil
  end

end

blog/app/helpers/test_form_helper.rb
module TestFormHelper
end

blog/app/helpers/user_helper.rb
module UserHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/edit.html.erb
<div class="container">
	<h3 class="page-header">Edit Article</h3>
	<% if @article && @article.errors.any? %>
	<div class="alert alert-danger">
		<% @article.errors.full_messages.each do |error| %>
		<span><%= error %></span>
		<% end %>
	</div>
	<% end %>
	<%= form_for :article, class:"form form-horizontal",  url:article_path(@article), method: :patch do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<br>
		<%= f.text_field :title, class:'form-control', value: @article.title %>
	</div>
	<div class="form-group">
		<%= f.label :text %>
		<br>
		<%= f.text_area :text, class:'form-control', value: @article.text %>
	</div>
	<div class="form-group">
		<%= f.submit "Save", class: "btn btn-primary" %>
	</div>
	<% end %>
	<p>
		<span>&laquo;</span><%= link_to "Back to Articles", articles_path %>
	</p>
</div>

blog/app/views/articles/index.html.erb
<div class="container">
	<h3 class="page-header">Listing Articles</h3>

	<p>
		<%= link_to "New Article", new_article_path %>
	</p>
	<table class="table table-striped table-hover table-bordered">
		<tr>
			<th>Title</th>
			<th>Text</th>
			<th>Actions</th>
		</tr>
		<% @articles.each do |article| %>
		<tr>
			<td><%= article.title %></td>
			<td class="oneliner"><%= article.text %></td>
			<td>
			<div class="btn-group btn-group-sm">
				<%= link_to "View", article_path(article.id), class: "btn btn-default" %>
				<%= link_to "Edit", edit_article_path(article.id), class: "btn btn-primary" %>
				<%= link_to "Delete", article_path(article),
				method: :delete,
				data: { confirm: "Are you sure?"},
				class: "btn btn-danger" %>
			</div></td>
		</tr>
		<% end %>
	</table>
</div>

blog/app/views/articles/new.html.erb
<div class="container">
	<h3 class="page-header">New Article</h3>

	<% if @article && @article.errors.any? %>
	<div class="alert alert-danger">
		<% @article.errors.full_messages.each do |error| %>
		<span><%= error %></span>
		<% end %>
	</div>
	<% end %>
	<%= form_for :article, class:"form form-horizontal",  url:articles_path do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<br>
		<%= f.text_field :title, placeholder: "Enter your title...",  class:'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :text %>
		<br>
		<%= f.text_area :text, placeholder: "Enter your text here", cols: '30', rows:'10', class:'form-control' %>
	</div>
	<div class="form-group">
		<%= f.submit "Save", class: 'btn btn-primary' %>
	</div>
	<% end %>
</div>

blog/app/views/articles/show.html.erb
<div class="container">


<!-- ARTICLE AREA -->
	<h3 class="page-header">View Article</h3>
	<%= link_to "New Article", new_article_path %>
	<span>&#124;</span> 
	<span>&laquo;</span><%= link_to "Back to Articles", articles_path %>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><%= @article.title %></h3>
		</div>
		<div class="panel-body">
			<p>
				<%= @article.text %>
			</p>
		</div>
	</div>




<!-- COMMENTS AREA -->
	<h4>Comments <span class="badge"><%= @article.comments.count %></span></h4>

	<!-- FORM -->
	<%= form_for([@article, @article.comments.build], html: {multipart: true}) do |f| %>
	  <div class="row">
	  	  <div class="col-sm-1">
	  	  	<%= image_tag current_user.image.url(:small) %>
	  	  </div>
		  <div class="form-group col-sm-10">
		    <%= f.text_area :body, placeholder: "Enter your comment...",  class:'form-control enter-submit' %>
		  </div>
  		  <div class="form-group">
			<%= f.submit "Post", class: 'btn btn-primary' %>
		  </div>
	  </div>
	<% end %>



	<!-- COMMENTS -->
	<div class="media-list">
		<% @article.comments.reverse.each do |comment| %>
		<hr>
		<div class="media">
			<div class="media-left">
				<% @comment_user = User.find_by(id:comment.user_id) %>
				<% if @comment_user != nil %>
					<a href="#">
						<%= image_tag @comment_user.image.url(:small), class: "thumbnail" %>
					</a>
				<% end %>
			</div>
			<div class="media-body">
				<a href="#">
					<%= @comment_user.name if @comment_user != nil %>
				</a>
				<p class="text-muted">
					<small><%= comment.updated_at.to_s.tr('UTC',' ') %></small>
				</p>
				<%= comment.body %>
			</div>
		</div>
		<% end %>
	</div>	<!-- media-list ends -->
	<br>

</div>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Blog</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

		<style>
			/* to limit text to one line in table cells */
			.table {
				table-layout:fixed;
			}
			.oneliner {
				overflow:hidden;
				white-space:nowrap;
				text-overflow:ellipsis;
			}
		</style>
	</head>
	<body>

		<nav class="navbar navbar-inverse navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" data-toggle="collapse" data-target="#navMenu" class="collapsed navbar-toggle">
						<span class="sr-only">Toggle Navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<span class="navbar-brand"><%= link_to "Blog", root_url, class: "navbar-link" %></span>
				</div>
				<div class="collapse navbar-collapse" id="navMenu">
					<ul class="nav navbar-nav navbar-right">
						<% if logged_in %>
						<li>
							<%= link_to "Articles", articles_path %>
						</li>
						<li class="dropdown">
							<a href="#" data-toggle="dropdown" role="button" class="dropdown-toggle">
								<%= image_tag current_user.image.url(:tiny) if current_user.image.exists?  %>
								<%= current_user.name %> <span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to "Profile", edit_user_path(current_user.id) %>
								</li>
								<li>
									<%= link_to "Sign Out", logout_path, method: "delete" %>
								</li>
							</ul>
						</li>
						<% else %>
						<% if login_path && !logged_in %>
						<li>
							<%= link_to "Sign In", login_path %>
						</li>
						<% end %>
						<li>
							<%= link_to "Sign up", new_user_path %>
						</li>
						<% end %>

					</ul>
				</div>
			</div>
		</nav>

		<%= yield %>

		<!-- JS AREA-->
		<script>
			$(function(){
				$(".enter-submit").keypress(function(e){
					if (e.which == 13) {
						//enter is pressed on that input field
						$(this).closest('form').submit();
					};
				});
			})

		</script>

	</body>
</html>

blog/app/views/test_form/index.html.erb
<h1>Test Form</h1>
<%= form_for :test_form, url:test_form_create_path do |f| %>
	<div>
		<%= f.label :title %><br>
		<%= f.text_field :title, placeholder: "Enter your title..." %>
	</div>
	<div>
		<%= f.label :text %><br>
		<%= f.text_area :text, placeholder: "Enter your text here", cols: '30', rows:'10' %>
	</div>
	<div>
		<%= f.submit "Save" %>
	</div>
<% end %>

blog/app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

blog/app/views/user/edit.html.erb
<% provide(:title, "Log in") %>

<div class="container">

	<div class="col-sm-push-4 col-sm-4">
		<% if @user && @user.errors.any? %>
		<div class="alert alert-danger">
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<h3 class="text-center">Edit Profile</h3>
		<%= form_for(:user, url: user_path, method: :patch, class:'form-horizontal') do |f| %>



		<div class="row">
			<div class="thumbnail">
				<%= image_tag @user.image.url(:medium), id:"image", width:300, height:300 %>
			</div>
		</div>

		<div class="form-group">
			<%= f.label "Profile Image", class: ' control-label' %>
			<%= f.file_field :image, class: 'form-control', id: 'image_file' %>
		</div>


		<div class="form-group">
			<%= f.label :name, class: 'control-label' %>
			<%= f.text_field :name, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :username, class: 'control-label' %>
			<%= f.text_field :username, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :email, class: 'control-label' %>
			<%= f.text_field :email, class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :password_digest, class: ' control-label' %>
			<%= f.password_field :password_digest, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :confirm_password, class: ' control-label' %>
			<%= f.password_field :confirm_password, class: 'form-control' %>
		</div>



		<div>
			<%= f.submit "Save", class: "btn btn-primary" %>
		</div>
		<% end %>
		<br>
	</div>
</div>


<!-- JS AREA -->
<script>
$(function(){
	$("#image_file").change(function() {
		var reader = new FileReader();

		reader.onload = function(e){
            $("#image").attr("src", e.target.result);
		}

		// console.info(this);
		reader.readAsDataURL(this.files[0]);
	})
})

</script>

blog/app/views/user/new.html.erb
<% provide(:title, "Log in") %>

<div class="container">

	<div class="col-sm-push-4 col-sm-4">
		<% if @user && @user.errors.any? %>
		<div class="alert alert-danger">
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<h3 class="text-center">Sign Up</h3>
		<%= form_for(:user, url: user_index_path, class:'form-horizontal') do |f| %>


		<div class="form-group">
			<%= f.label "Profile Image", class: ' control-label' %>
			<div class="thumbnail">
				<img src="/images/missing.png" id="image" width=200 height=200 alt="Profile pic">
			</div>
			<%= f.file_field :image, class: 'form-control', id: "image_file" %>
		</div>

		<div class="form-group">
			<%= f.label :name, class: 'control-label' %>
			<%= f.text_field :name, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :username, class: 'control-label' %>
			<%= f.text_field :username, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :email, class: 'control-label' %>
			<%= f.text_field :email, class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :password_digest, class: ' control-label' %>
			<%= f.password_field :password_digest, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :confirm_password, class: ' control-label' %>
			<%= f.password_field :confirm_password, class: 'form-control' %>
		</div>



		<div>
			<%= f.submit "Sign Up", class: "btn btn-primary" %>
		</div>
		<% end %>
		<br>
		<p>
			Already a user? <%= link_to "Log In", login_path %>
		</p>
	</div>
</div>


<!-- JS AREA -->
<script>
$(function(){
	$("#image_file").change(function() {
		var reader = new FileReader();

		reader.onload = function(e){
            $("#image").attr("src", e.target.result);
		}

		// console.info(this);
		reader.readAsDataURL(this.files[0]);
	})
})

</script>

blog/app/views/user/update.html.erb
<div class="container">
	<h4 class="alert alert-success">Your profile has been updated successfully!</h4>
	<%= link_to "Back to homepage", articles_path %>
</div>

blog/app/views/welcome/about_us.html.erb
<div class="container">
	<h1>About us</h1>
	<p>
	We are group CMMR and our members are -
	</p>
	<ul>
		<% @names.each do |name| %>
		<li><%= name %></li>
		<% end %>
	</ul>
</div>

blog/app/views/welcome/index.html.erb
<div class="container">
	<h1>Welcome To CMMR blog</h1>
	<p>Find out <%= link_to "About us", welcome_about_us_path %></p>
</div>